### ISSUE TITLE
bugs in createCylinderWithHoles

### ISSUE THREAD

**Issue by makc** [hofk/THREEi.js#2]
```
	THREEi.createCylinderWithHoles.call( geometry, {
		d: 0.08, // rough side length of the triangles
		div4: 10, // division of the quarter circle
		bottom: -2, 
		top: 2,
		holes: [
			// circular (deformed) hole, 3 elements: [ y, phi, div4Hole ], div4Hole <= div4	
			[ 0, 0, 20 ],
			//points hole,: array of points y, phi, ...  (last point is connected to first)
			[ 0.33,2.9, -0.33,2.9, -0.33,3.38, 0.33,3.38 ]
		]
	} );
```
=>
```
TypeError: can't access property "idx", insertFront[0] is undefined THREEi.js:2718:4
    makeNewTriangles https://rawcdn.githack.com/hofk/THREEi.js/7efc02901ae7aadeaaa8e46301e5719d72527005/THREEi.js:2718
    trianglesAtSplitPoints https://rawcdn.githack.com/hofk/THREEi.js/7efc02901ae7aadeaaa8e46301e5719d72527005/THREEi.js:2608
    buildCylinderWithHoles https://rawcdn.githack.com/hofk/THREEi.js/7efc02901ae7aadeaaa8e46301e5719d72527005/THREEi.js:2160
    createCylinderWithHoles https://rawcdn.githack.com/hofk/THREEi.js/7efc02901ae7aadeaaa8e46301e5719d72527005/THREEi.js:2026
```

same code with
```
div4: 20,
```
=>
```
TypeError: can't access property "ang", front[m] is undefined THREEi.js:2640:3
    makeNewTriangles https://rawcdn.githack.com/hofk/THREEi.js/7efc02901ae7aadeaaa8e46301e5719d72527005/THREEi.js:2640
    buildCylinderWithHoles https://rawcdn.githack.com/hofk/THREEi.js/7efc02901ae7aadeaaa8e46301e5719d72527005/THREEi.js:2133
    createCylinderWithHoles https://rawcdn.githack.com/hofk/THREEi.js/7efc02901ae7aadeaaa8e46301e5719d72527005/THREEi.js:2026
```

I get it, it says ` div4Hole <= div4	` but cant you put div4 = Math.max(div4, all of div4Hole-s) or something

**Comment by makc** [comment]
another issue is that it creates a ton of unused 0,0,0 vertices

**Comment by hofk** [comment]
The problem with triangulation is that it works in many cases but not in all circumstances. Since the algorithm by E. Hartmann is very complex, it is often not possible to draw any direct conclusions from the error messages.The fronts of the holes must not come too close, the holes must not be too small, etc.

Sometimes a small change helps and it works.

To see what happens, remove the // on DEBUG triangles and counts the triangles stp ++;

In the ------ triangulation cycle ----------

 you then set 

//////// DEBUG triangles /// 
  if ( stp > 100 ) break;
	 
or a smaller/larger number.
 And uses the draw range slider

---

Since the number of triangles is difficult to see in advance, I have chosen very generously.

After a test you can reduce the arrays.
